fix: remove await from sync must_get_auth_ctx calls
must_get_auth_ctx is a sync function, not async. Using await caused
TypeError: object Request can't be used in 'await' expression